# Generated by Django 5.2.7 on 2025-10-19 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("symbol", models.CharField(blank=True, max_length=20)),
                (
                    "current_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Annuity",
            fields=[
                (
                    "investment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="investco.investment",
                    ),
                ),
                (
                    "annuity_type",
                    models.CharField(
                        choices=[
                            ("FIXED", "Fixed Annuity"),
                            ("VARIABLE", "Variable Annuity"),
                            ("IMMEDIATE", "Immediate Annuity"),
                            ("DEFERRED", "Deferred Annuity"),
                            ("INDEXED", "Indexed Annuity"),
                        ],
                        max_length=20,
                    ),
                ),
                ("insurance_company", models.CharField(max_length=200)),
                ("policy_number", models.CharField(max_length=100)),
                (
                    "guaranteed_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("payout_start_date", models.DateField(blank=True, null=True)),
                (
                    "monthly_payout",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("surrender_charge_period", models.IntegerField(blank=True, null=True)),
                (
                    "death_benefit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "rider_fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "premium_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total premiums paid (cost basis)",
                        max_digits=12,
                    ),
                ),
                (
                    "cash_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current cash/surrender value",
                        max_digits=12,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("investco.investment",),
        ),
        migrations.CreateModel(
            name="Bond",
            fields=[
                (
                    "investment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="investco.investment",
                    ),
                ),
                (
                    "shares",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Number of shares/units/coins",
                        max_digits=15,
                    ),
                ),
                (
                    "average_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Average cost per share/unit",
                        max_digits=10,
                    ),
                ),
                (
                    "bond_type",
                    models.CharField(
                        choices=[
                            ("GOVERNMENT", "Government Bond"),
                            ("CORPORATE", "Corporate Bond"),
                            ("MUNICIPAL", "Municipal Bond"),
                            ("TREASURY", "Treasury Bond"),
                        ],
                        max_length=20,
                    ),
                ),
                ("face_value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("coupon_rate", models.DecimalField(decimal_places=4, max_digits=5)),
                ("maturity_date", models.DateField()),
                ("issuer", models.CharField(max_length=200)),
                ("credit_rating", models.CharField(blank=True, max_length=10)),
                (
                    "yield_to_maturity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("investco.investment",),
        ),
        migrations.CreateModel(
            name="Cryptocurrency",
            fields=[
                (
                    "investment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="investco.investment",
                    ),
                ),
                (
                    "shares",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Number of shares/units/coins",
                        max_digits=15,
                    ),
                ),
                (
                    "average_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Average cost per share/unit",
                        max_digits=10,
                    ),
                ),
                (
                    "crypto_type",
                    models.CharField(
                        choices=[
                            ("BITCOIN", "Bitcoin"),
                            ("ETHEREUM", "Ethereum"),
                            ("ALTCOIN", "Altcoin"),
                            ("STABLECOIN", "Stablecoin"),
                            ("DEFI", "DeFi Token"),
                            ("NFT", "NFT Collection"),
                        ],
                        max_length=20,
                    ),
                ),
                ("blockchain", models.CharField(blank=True, max_length=100)),
                ("wallet_address", models.CharField(blank=True, max_length=200)),
                ("exchange", models.CharField(blank=True, max_length=100)),
                (
                    "staking_rewards",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "staking_apy",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("market_cap_rank", models.IntegerField(blank=True, null=True)),
                (
                    "circulating_supply",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "max_supply",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("investco.investment",),
        ),
        migrations.CreateModel(
            name="ETF",
            fields=[
                (
                    "investment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="investco.investment",
                    ),
                ),
                (
                    "shares",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Number of shares/units/coins",
                        max_digits=15,
                    ),
                ),
                (
                    "average_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Average cost per share/unit",
                        max_digits=10,
                    ),
                ),
                ("fund_name", models.CharField(max_length=200)),
                ("expense_ratio", models.DecimalField(decimal_places=4, max_digits=5)),
                (
                    "nav",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "assets_under_management",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("inception_date", models.DateField(blank=True, null=True)),
                ("benchmark_index", models.CharField(blank=True, max_length=200)),
                ("dividend_frequency", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "abstract": False,
            },
            bases=("investco.investment",),
        ),
        migrations.CreateModel(
            name="MutualFund",
            fields=[
                (
                    "investment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="investco.investment",
                    ),
                ),
                (
                    "shares",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Number of shares/units/coins",
                        max_digits=15,
                    ),
                ),
                (
                    "average_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Average cost per share/unit",
                        max_digits=10,
                    ),
                ),
                (
                    "fund_type",
                    models.CharField(
                        choices=[
                            ("EQUITY", "Equity Fund"),
                            ("BOND", "Bond Fund"),
                            ("BALANCED", "Balanced Fund"),
                            ("INDEX", "Index Fund"),
                            ("TARGET_DATE", "Target Date Fund"),
                            ("MONEY_MARKET", "Money Market Fund"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fund_name", models.CharField(max_length=200)),
                ("expense_ratio", models.DecimalField(decimal_places=4, max_digits=5)),
                (
                    "nav",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "minimum_investment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("fund_manager", models.CharField(blank=True, max_length=200)),
                ("inception_date", models.DateField(blank=True, null=True)),
                (
                    "load_fee",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("investco.investment",),
        ),
        migrations.CreateModel(
            name="OtherInvestment",
            fields=[
                (
                    "investment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="investco.investment",
                    ),
                ),
                (
                    "investment_category",
                    models.CharField(
                        choices=[
                            ("COMMODITY", "Commodity"),
                            ("COLLECTIBLE", "Collectible"),
                            ("PRECIOUS_METALS", "Precious Metals"),
                            ("PRIVATE_EQUITY", "Private Equity"),
                            ("HEDGE_FUND", "Hedge Fund"),
                            ("VENTURE_CAPITAL", "Venture Capital"),
                            ("OPTIONS", "Options"),
                            ("FUTURES", "Futures"),
                            ("FOREX", "Foreign Exchange"),
                            ("STRUCTURED_PRODUCT", "Structured Product"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("custodian", models.CharField(blank=True, max_length=200)),
                ("maturity_date", models.DateField(blank=True, null=True)),
                ("risk_rating", models.CharField(blank=True, max_length=20)),
                ("liquidity_timeframe", models.CharField(blank=True, max_length=100)),
                (
                    "minimum_investment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "management_fee",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "cost_basis",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total amount invested",
                        max_digits=12,
                    ),
                ),
                (
                    "market_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current market value",
                        max_digits=12,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("investco.investment",),
        ),
        migrations.CreateModel(
            name="RealEstate",
            fields=[
                (
                    "investment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="investco.investment",
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("RESIDENTIAL", "Residential Property"),
                            ("COMMERCIAL", "Commercial Property"),
                            ("INDUSTRIAL", "Industrial Property"),
                            ("LAND", "Raw Land"),
                            ("REIT", "Real Estate Investment Trust"),
                            ("RENTAL", "Rental Property"),
                        ],
                        max_length=20,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "appraised_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "monthly_rental_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "monthly_expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "property_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "insurance_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "mortgage_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("square_footage", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("investco.investment",),
        ),
        migrations.CreateModel(
            name="Retirement401k",
            fields=[
                (
                    "investment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="investco.investment",
                    ),
                ),
                (
                    "contribution_type",
                    models.CharField(
                        choices=[
                            ("TRADITIONAL", "Traditional 401(k)"),
                            ("ROTH", "Roth 401(k)"),
                            ("SAFE_HARBOR", "Safe Harbor 401(k)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("employer_name", models.CharField(max_length=200)),
                ("plan_name", models.CharField(max_length=200)),
                (
                    "employee_contribution_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "employer_match_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("vesting_schedule", models.CharField(blank=True, max_length=200)),
                (
                    "loan_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "annual_contribution_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_contributions",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total cost basis",
                        max_digits=12,
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current total value",
                        max_digits=12,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("investco.investment",),
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "investment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="investco.investment",
                    ),
                ),
                (
                    "shares",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Number of shares/units/coins",
                        max_digits=15,
                    ),
                ),
                (
                    "average_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Average cost per share/unit",
                        max_digits=10,
                    ),
                ),
                ("ticker_symbol", models.CharField(max_length=10)),
                ("company_name", models.CharField(max_length=200)),
                ("sector", models.CharField(blank=True, max_length=100)),
                (
                    "market_cap",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "pe_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "dividend_yield",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("exchange", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "abstract": False,
            },
            bases=("investco.investment",),
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="investment",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investments",
                to="investco.portfolio",
            ),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("BUY", "Buy"),
                            ("SELL", "Sell"),
                            ("DIVIDEND", "Dividend"),
                            ("SPLIT", "Stock Split"),
                            ("PREMIUM", "Premium Payment"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "shares",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=15, null=True
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="For lump-sum transactions like premium payments",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("date", models.DateTimeField()),
                ("notes", models.TextField(blank=True)),
                (
                    "investment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="investco.investment",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="InvestmentValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateTimeField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("volume", models.BigIntegerField(blank=True, null=True)),
                (
                    "market_cap",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("source", models.CharField(default="manual", max_length=50)),
                (
                    "investment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_values",
                        to="investco.investment",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["investment", "date"],
                        name="investco_in_investm_dac6ef_idx",
                    ),
                    models.Index(fields=["date"], name="investco_in_date_317f77_idx"),
                ],
                "unique_together": {("investment", "date")},
            },
        ),
        migrations.CreateModel(
            name="PredictionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("LINEAR_REGRESSION", "Linear Regression"),
                            ("MOVING_AVERAGE", "Moving Average"),
                            ("ARIMA", "ARIMA"),
                            ("LSTM", "LSTM Neural Network"),
                        ],
                        max_length=20,
                    ),
                ),
                ("prediction_date", models.DateTimeField()),
                (
                    "predicted_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "confidence_interval_low",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "confidence_interval_high",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "accuracy_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("training_period_days", models.IntegerField()),
                ("model_parameters", models.JSONField(blank=True, null=True)),
                (
                    "investment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="investco.investment",
                    ),
                ),
            ],
            options={
                "ordering": ["-prediction_date"],
                "indexes": [
                    models.Index(
                        fields=["investment", "prediction_date"],
                        name="investco_pr_investm_a0d5be_idx",
                    ),
                    models.Index(
                        fields=["model_type", "created_at"],
                        name="investco_pr_model_t_a4bdc8_idx",
                    ),
                ],
            },
        ),
    ]
