# Generated by Django 5.2.7 on 2025-10-19 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investco", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="annuity",
            options={"verbose_name_plural": "Annuities"},
        ),
        migrations.RemoveField(
            model_name="annuity",
            name="premium_paid",
        ),
        migrations.CreateModel(
            name="GuaranteedWithdrawalBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Guaranteed withdrawal balance at this point in time",
                        max_digits=12,
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(help_text="Date this balance became effective"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Reason for change (e.g., premium payment, step-up, withdrawal)",
                    ),
                ),
                (
                    "annuity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gwb_history",
                        to="investco.annuity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guaranteed Withdrawal Balance",
                "verbose_name_plural": "Guaranteed Withdrawal Balances",
                "ordering": ["-effective_date"],
            },
        ),
    ]
