# Generated by Django 5.2.7 on 2025-10-20 13:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investco", "0002_alter_annuity_options_remove_annuity_premium_paid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="annuity",
            name="issue_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Date the annuity contract was issued",
            ),
            preserve_default=False,
        ),
    ]
