# Generated by Django 5.2.7 on 2025-10-26 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("investco", "0004_add_annuity_transaction_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("statement_date", models.DateField(help_text="Date of the statement")),
                (
                    "period_start",
                    models.DateField(help_text="Start date of statement period"),
                ),
                (
                    "period_end",
                    models.DateField(help_text="End date of statement period"),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        help_text="Upload statement PDF/image",
                        null=True,
                        upload_to="statements/",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "investment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statements",
                        to="investco.investment",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-statement_date"],
            },
        ),
        migrations.RemoveField(
            model_name="annuity",
            name="cash_value",
        ),
        migrations.CreateModel(
            name="AnnuityStatement",
            fields=[
                (
                    "statement_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="investco.statement",
                    ),
                ),
                (
                    "beginning_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Account value at beginning of period",
                        max_digits=12,
                    ),
                ),
                (
                    "ending_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Account value at end of period",
                        max_digits=12,
                    ),
                ),
                (
                    "premiums",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Premium payments during period",
                        max_digits=12,
                    ),
                ),
                (
                    "net_change",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Net investment gain/loss during period",
                        max_digits=12,
                    ),
                ),
                (
                    "withdrawals",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Withdrawals during period",
                        max_digits=12,
                    ),
                ),
                (
                    "tax_withholding",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tax withholding during period",
                        max_digits=12,
                    ),
                ),
                (
                    "remaining_guaranteed_balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Remaining guaranteed balance",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "death_benefit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Death benefit amount",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "earnings_determination_baseline",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Baseline for earnings determination",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "guaranteed_withdrawal_balance_bonus_baseline",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="GWB bonus baseline",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "guaranteed_withdrawal_amount_annually",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual guaranteed withdrawal amount (can be N/A)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "guaranteed_withdrawal_amount_remaining",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Guaranteed withdrawal amount remaining this year (can be N/A)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "percent_of_guaranteed_available_for_withdrawal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Percent of guaranteed amount available for withdrawal (e.g., 0.05 for 5%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Annuity Statement",
                "verbose_name_plural": "Annuity Statements",
            },
            bases=("investco.statement",),
        ),
        migrations.AddIndex(
            model_name="statement",
            index=models.Index(
                fields=["investment", "statement_date"],
                name="investco_st_investm_8814c7_idx",
            ),
        ),
    ]
