# Generated by Django 5.2.7 on 2025-10-26 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "investco",
            "0005_statement_remove_annuity_cash_value_annuitystatement_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="source_statement",
            field=models.ForeignKey(
                blank=True,
                help_text="Statement that generated this transaction (if auto-generated)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_transactions",
                to="investco.statement",
            ),
        ),
    ]
