# Generated by Django 5.2.7 on 2025-11-09 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investco", "0006_transaction_source_statement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Retirement401kStatement",
            fields=[
                (
                    "statement_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="investco.statement",
                    ),
                ),
                (
                    "beginning_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Account balance at beginning of period",
                        max_digits=12,
                    ),
                ),
                (
                    "ending_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Account balance at end of period",
                        max_digits=12,
                    ),
                ),
                (
                    "employee_contributions",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Employee contributions during period",
                        max_digits=12,
                    ),
                ),
                (
                    "employer_contributions",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Employer contributions/match during period",
                        max_digits=12,
                    ),
                ),
                (
                    "investment_gain_loss",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Investment gains or losses during period",
                        max_digits=12,
                    ),
                ),
                (
                    "withdrawals",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Withdrawals during period",
                        max_digits=12,
                    ),
                ),
                (
                    "fees",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Fees charged during period",
                        max_digits=12,
                    ),
                ),
                (
                    "loan_payments",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Loan payments during period",
                        max_digits=12,
                    ),
                ),
                (
                    "vested_balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Vested balance (amount you can take if you leave)",
                        max_digits=12,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "401k Statement",
                "verbose_name_plural": "401k Statements",
            },
            bases=("investco.statement",),
        ),
    ]
