# Generated by Django 5.2.7 on 2025-11-09 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investco", "0007_retirement401kstatement"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrokerageAccount",
            fields=[
                (
                    "investment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="investco.investment",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual Taxable Account"),
                            ("JOINT", "Joint Taxable Account"),
                            ("IRA_TRADITIONAL", "Traditional IRA"),
                            ("IRA_ROTH", "Roth IRA"),
                            ("SEP_IRA", "SEP IRA"),
                            ("SIMPLE_IRA", "SIMPLE IRA"),
                            ("ROLLOVER_IRA", "Rollover IRA"),
                            ("CUSTODIAL", "Custodial Account (UGMA/UTMA)"),
                            ("TRUST", "Trust Account"),
                            ("MARGIN", "Margin Account"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "brokerage_firm",
                    models.CharField(
                        help_text="Name of brokerage (e.g., Fidelity, Vanguard, Schwab)",
                        max_length=200,
                    ),
                ),
                ("account_number", models.CharField(blank=True, max_length=100)),
                (
                    "tax_advantaged",
                    models.BooleanField(
                        default=False,
                        help_text="Is this a tax-advantaged account (IRA, 401k, etc.)?",
                    ),
                ),
                (
                    "margin_enabled",
                    models.BooleanField(
                        default=False, help_text="Is margin trading enabled?"
                    ),
                ),
                (
                    "cash_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cash available in account",
                        max_digits=12,
                    ),
                ),
                (
                    "total_cost_basis",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total amount invested",
                        max_digits=12,
                    ),
                ),
                (
                    "current_market_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current total value",
                        max_digits=12,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("investco.investment",),
        ),
    ]
