# Generated by Django 5.2.7 on 2025-11-09 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investco", "0008_brokerageaccount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brokerageaccount",
            options={
                "verbose_name": "Brokerage Account",
                "verbose_name_plural": "Brokerage Accounts",
            },
        ),
        migrations.AlterModelOptions(
            name="retirement401k",
            options={
                "verbose_name": "401(k) Retirement Account",
                "verbose_name_plural": "401(k) Retirement Accounts",
            },
        ),
        migrations.AlterModelOptions(
            name="stock",
            options={"verbose_name": "Stock", "verbose_name_plural": "Stocks"},
        ),
    ]
