# Generated by Django 5.2.7 on 2025-11-09 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investco", "0009_alter_brokerageaccount_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrokerageAccountStatement",
            fields=[
                (
                    "statement_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="investco.statement",
                    ),
                ),
                (
                    "beginning_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Account value at beginning of period",
                        max_digits=12,
                    ),
                ),
                (
                    "ending_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Account value at end of period",
                        max_digits=12,
                    ),
                ),
                (
                    "deposits",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cash deposits/contributions during period",
                        max_digits=12,
                    ),
                ),
                (
                    "withdrawals",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cash withdrawals/distributions during period",
                        max_digits=12,
                    ),
                ),
                (
                    "dividends",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Dividends received during period",
                        max_digits=12,
                    ),
                ),
                (
                    "interest",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Interest earned during period",
                        max_digits=12,
                    ),
                ),
                (
                    "capital_gains",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Realized capital gains during period (can be negative for losses)",
                        max_digits=12,
                    ),
                ),
                (
                    "fees",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Fees and expenses charged during period",
                        max_digits=12,
                    ),
                ),
                (
                    "other_activity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Other activity (transfers, corporate actions, etc.)",
                        max_digits=12,
                    ),
                ),
                (
                    "market_change",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Unrealized gain/loss from market value changes",
                        max_digits=12,
                    ),
                ),
                (
                    "total_cost_basis",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total cost basis of holdings",
                        max_digits=12,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Brokerage Account Statement",
                "verbose_name_plural": "Brokerage Account Statements",
            },
            bases=("investco.statement",),
        ),
    ]
