# Generated by Django 5.2.7 on 2025-11-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investco", "0010_brokerageaccountstatement"),
    ]

    operations = [
        migrations.AddField(
            model_name="brokerageaccountstatement",
            name="equities",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount allocated to equities/stocks",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="brokerageaccountstatement",
            name="fixed_income",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount allocated to fixed income/bonds",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="brokerageaccountstatement",
            name="money_market",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount allocated to money market funds",
                max_digits=12,
                null=True,
            ),
        ),
    ]
