# Generated by Django 5.2.7 on 2025-11-16 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investco", "0011_brokerageaccountstatement_equities_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="retirement_date",
            field=models.DateField(
                blank=True,
                help_text="Target retirement date for planning purposes",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="RetirementPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expected_return",
                    models.DecimalField(
                        decimal_places=2,
                        default=7.0,
                        help_text="Expected annual return percentage (e.g., 7.00 for 7%)",
                        max_digits=5,
                    ),
                ),
                (
                    "continued_investment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount of continued contributions",
                        max_digits=12,
                    ),
                ),
                (
                    "continued_investment_frequency",
                    models.CharField(
                        choices=[("MONTHLY", "Monthly"), ("ANNUAL", "Annual")],
                        default="MONTHLY",
                        help_text="Frequency of continued contributions",
                        max_length=10,
                    ),
                ),
                (
                    "withdrawal_type",
                    models.CharField(
                        choices=[
                            ("PERCENTAGE", "Percentage"),
                            ("FIXED_AMOUNT", "Fixed Amount"),
                        ],
                        default="PERCENTAGE",
                        help_text="Type of withdrawal strategy",
                        max_length=15,
                    ),
                ),
                (
                    "withdrawal_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=4.0,
                        help_text="Annual withdrawal percentage (e.g., 4.00 for 4%)",
                        max_digits=5,
                    ),
                ),
                (
                    "withdrawal_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Fixed annual withdrawal amount",
                        max_digits=12,
                    ),
                ),
                (
                    "investment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retirement_plan",
                        to="investco.investment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retirement Plan",
                "verbose_name_plural": "Retirement Plans",
            },
        ),
    ]
