# Generated by Django 5.2.7 on 2025-11-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investco", "0012_portfolio_retirement_date_retirementplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="retirementplan",
            name="contribution_years",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Number of years to continue contributions (leave blank to contribute until retirement)",
                max_digits=5,
                null=True,
            ),
        ),
    ]
