# Generated by Django 5.2.7 on 2025-11-16 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investco", "0013_retirementplan_contribution_years"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialSecurityBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "beneficiary_name",
                    models.CharField(
                        help_text="Name of the Social Security beneficiary",
                        max_length=200,
                    ),
                ),
                (
                    "estimated_monthly_benefit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Estimated monthly benefit at full retirement age",
                        max_digits=10,
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True,
                        help_text="Birth date for calculating retirement age",
                        null=True,
                    ),
                ),
                (
                    "full_retirement_age",
                    models.DecimalField(
                        decimal_places=1,
                        default=67.0,
                        help_text="Full retirement age (e.g., 67.0, 66.5)",
                        max_digits=4,
                    ),
                ),
                (
                    "planned_start_age",
                    models.DecimalField(
                        decimal_places=1,
                        default=67.0,
                        help_text="Age when you plan to start taking benefits",
                        max_digits=4,
                    ),
                ),
                (
                    "early_reduction_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Annual reduction percentage for early claiming (e.g., 6.67 for ~6.67%/year)",
                        max_digits=5,
                    ),
                ),
                (
                    "delayed_increase_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        help_text="Annual increase percentage for delayed claiming (typically 8%/year)",
                        max_digits=5,
                    ),
                ),
                (
                    "assume_cola",
                    models.BooleanField(
                        default=True,
                        help_text="Apply annual cost of living adjustments",
                    ),
                ),
                (
                    "estimated_cola_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.5,
                        help_text="Estimated annual COLA percentage (e.g., 2.5 for 2.5%)",
                        max_digits=4,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about Social Security benefits",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_security_benefits",
                        to="investco.portfolio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Security Benefit",
                "verbose_name_plural": "Social Security Benefits",
                "ordering": ["beneficiary_name"],
            },
        ),
    ]
