# Generated by Django 5.2.7 on 2025-11-16 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investco", "0014_socialsecuritybenefit"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomeStream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name or description of this income stream",
                        max_length=200,
                    ),
                ),
                (
                    "income_type",
                    models.CharField(
                        choices=[
                            ("PENSION", "Pension"),
                            ("RENTAL", "Rental Income"),
                            ("ANNUITY_PAYMENT", "Annuity Payment"),
                            ("PART_TIME", "Part-Time Work"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        help_text="Type of income stream",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount per payment period",
                        max_digits=10,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUAL", "Annual"),
                        ],
                        default="MONTHLY",
                        help_text="How often payments are received",
                        max_length=20,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="When this income stream starts (leave blank if already started)",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="When this income stream ends (leave blank for indefinite)",
                        null=True,
                    ),
                ),
                (
                    "is_guaranteed",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this income is guaranteed (e.g., pension vs. potential rental income)",
                    ),
                ),
                (
                    "assume_cola",
                    models.BooleanField(
                        default=False, help_text="Assume cost of living adjustments"
                    ),
                ),
                (
                    "estimated_cola_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Estimated annual COLA percentage (e.g., 2.5 for 2.5%)",
                        max_digits=4,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this income stream",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        help_text="Portfolio this income stream belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="income_streams",
                        to="investco.portfolio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Income Stream",
                "verbose_name_plural": "Income Streams",
                "ordering": ["name"],
            },
        ),
    ]
