# Generated by Django 5.2.7 on 2026-02-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investco", "0015_incomestream"),
    ]

    operations = [
        migrations.AddField(
            model_name="statement",
            name="off_statement_adjustment",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Adjustment for off-statement changes (e.g., premium reversals). Added to beginning value for chain calculations.",
                max_digits=12,
            ),
        ),
    ]
